#!/bin/bash

GHOSTTY_CONFIG="$HOME/.config/ghostty/config"

THEMES=(
  "Afterglow"
  "Atom One Dark"
  "Ayu Mirage"
  "Breeze"
  "Catppuccin Macchiato"
  "Cobalt Next Dark"
  "Cobalt2"
  "Cyberpunk Scarlet Protocol"
  "DarkMatrix"
  "DuckBones"
  "Duotone Dark"
  "Elemental"
  "ENCOM"
  "Forest Blue"
  "Front End Delight"
  "Galaxy"
  "Glacier"
  "Gruvbox Material Dark"
  "Hardcore"
  "HaX0R Gr33N"
  "Heeler"
  "Hipster Green"
  "Hivacruz"
  "Horizon"
  "IC Green PPL"
  "Iceberg Dark"
  "iTerm2 Solarized Dark"
  "Kanagawabones"
  "Lab Fox"
  "Lavandula"
  "Lovelace"
  "Material Design Colors"
  "Material Ocean"
  "Matrix"
  "Matte Black"
  "Mellow"
  "Mirage"
  "Monokai Pro Machine"
  "Monokai Pro Octagon"
  "Neon"
  "Night Owl"
  "Nightfox"
  "Nocturnal Winter"
  "Obsidian"
  "Oceanic Material"
  "Ollie"
  "One Double Dark"
  "Overnight Slumber"
  "Oxocarbon"
  "Pencil Dark"
  "Popping and Locking"
  "Rapture"
  "Retro Legends"
  "Rose Pine Moon"
  "Sea Shells"
  "Shaman"
  "Sleepy Hollow"
  "Snazzy"
  "Solarized Dark Higher Contrast"
  "Spacedust"
  "Spacegray Eighties"
  "Sublette"
  "Terafox"
  "Tomorrow Night Burns"
  "Toy Chest"
  "Treehouse"
  "Under The Sea"
  "Urple"
  "Violet Dark"
  "Whimsy"
  "Zenwritten Dark"
)

RANDOM_THEME=${THEMES[$RANDOM % ${#THEMES[@]}]}

if grep -q "^theme = " "$GHOSTTY_CONFIG"; then
  sed -i '' "s/^theme = .*/theme = $RANDOM_THEME/" "$GHOSTTY_CONFIG"
else
  echo "theme = $RANDOM_THEME" >> "$GHOSTTY_CONFIG"
fi
